# Generated by Django 5.2.7 on 2025-11-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CekEmosi',
            fields=[
                ('id_cek', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('link_yt', models.CharField(blank=True, max_length=200, null=True)),
                ('hasil_deteksi', models.CharField(max_length=20)),
                ('detail_hasil', models.TextField()),
                ('jumlah_comment', models.IntegerField(default=1)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Deteksi Emosi',
                'verbose_name_plural': 'Riwayat Deteksi Emosi',
                'db_table': 'cek_emosi',
                'ordering': ['-tanggal'],
            },
        ),
    ]
